integer(c_int), parameter :: BLIS_NO_TRANSPOSE      = 0
integer(c_int), parameter :: BLIS_TRANSPOSE         = 8
integer(c_int), parameter :: BLIS_CONJ_NO_TRANSPOSE = 16
integer(c_int), parameter :: BLIS_CONJ_TRANSPOSE    = 24

integer(c_int), parameter :: BLIS_NO_CONJUGATE = 0
integer(c_int), parameter :: BLIS_CONJUGATE    = 16

integer(c_int), parameter :: BLIS_LEFT  = 0
integer(c_int), parameter :: BLIS_RIGHT = 1

integer(c_int), parameter :: BLIS_LOWER = 192
integer(c_int), parameter :: BLIS_UPPER = 96
integer(c_int), parameter :: BLIS_DENSE = 224

integer(c_int), parameter :: BLIS_NONUNIT_DIAG = 0
integer(c_int), parameter :: BLIS_UNIT_DIAG    = 256

